# 前端镜像:多阶段构建,Vite 产物 → nginx 提供
# 构建参数(在未来云「构建模板」或 docker build --build-arg 传入):
#   VITE_TEABLE_API_BASE / VITE_TEABLE_TOKEN / VITE_TEABLE_*_TABLE_ID 等
#   VITE_SSO_APPID / VITE_SSO_WORKER_BASE
#   VITE_AI_API_BASE / VITE_AI_API_KEY / VITE_AI_MODEL
#   VITE_OPENROUTER_KEY / VITE_OPENROUTER_MODEL
#   VITE_GITHUB_TOKEN / VITE_GITHUB_REPO / VITE_SHUHUAN_WEBHOOK

FROM hub.tal.com/standard/node:18 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_TEABLE_API_BASE
ARG VITE_TEABLE_TOKEN
ARG VITE_TEABLE_USERS_TABLE_ID
ARG VITE_TEABLE_PROJECTS_TABLE_ID
ARG VITE_TEABLE_TOOLS_TABLE_ID
ARG VITE_TEABLE_REVIEWS_TABLE_ID
ARG VITE_TEABLE_CONSULTING_TABLE_ID
ARG VITE_TEABLE_ANALYTICS_TABLE_ID
ARG VITE_TEABLE_AI_TABLE_ID
ARG VITE_TEABLE_OKR_TABLE_ID
ARG VITE_TEABLE_COST_LEDGER_TABLE_ID=tbl4e5Cuu6nlNw19uqz
ARG VITE_SHUHUAN_WEBHOOK
ARG VITE_AI_API_KEY
ARG VITE_AI_API_BASE
ARG VITE_AI_MODEL
ARG VITE_OPENROUTER_KEY
ARG VITE_OPENROUTER_MODEL
ARG VITE_GITHUB_TOKEN
ARG VITE_GITHUB_REPO
ARG VITE_SSO_APPID
ARG VITE_SSO_WORKER_BASE

ENV VITE_TEABLE_API_BASE=$VITE_TEABLE_API_BASE \
    VITE_TEABLE_TOKEN=$VITE_TEABLE_TOKEN \
    VITE_TEABLE_USERS_TABLE_ID=$VITE_TEABLE_USERS_TABLE_ID \
    VITE_TEABLE_PROJECTS_TABLE_ID=$VITE_TEABLE_PROJECTS_TABLE_ID \
    VITE_TEABLE_TOOLS_TABLE_ID=$VITE_TEABLE_TOOLS_TABLE_ID \
    VITE_TEABLE_REVIEWS_TABLE_ID=$VITE_TEABLE_REVIEWS_TABLE_ID \
    VITE_TEABLE_CONSULTING_TABLE_ID=$VITE_TEABLE_CONSULTING_TABLE_ID \
    VITE_TEABLE_ANALYTICS_TABLE_ID=$VITE_TEABLE_ANALYTICS_TABLE_ID \
    VITE_TEABLE_AI_TABLE_ID=$VITE_TEABLE_AI_TABLE_ID \
    VITE_TEABLE_OKR_TABLE_ID=$VITE_TEABLE_OKR_TABLE_ID \
    VITE_TEABLE_COST_LEDGER_TABLE_ID=$VITE_TEABLE_COST_LEDGER_TABLE_ID \
    VITE_SHUHUAN_WEBHOOK=$VITE_SHUHUAN_WEBHOOK \
    VITE_AI_API_KEY=$VITE_AI_API_KEY \
    VITE_AI_API_BASE=$VITE_AI_API_BASE \
    VITE_AI_MODEL=$VITE_AI_MODEL \
    VITE_OPENROUTER_KEY=$VITE_OPENROUTER_KEY \
    VITE_OPENROUTER_MODEL=$VITE_OPENROUTER_MODEL \
    VITE_GITHUB_TOKEN=$VITE_GITHUB_TOKEN \
    VITE_GITHUB_REPO=$VITE_GITHUB_REPO \
    VITE_SSO_APPID=$VITE_SSO_APPID \
    VITE_SSO_WORKER_BASE=$VITE_SSO_WORKER_BASE

RUN npm run build

FROM hub.tal.com/standard/nginx:1.20.1-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
